package cc.ashclaw.common4j.core.id;

import java.time.Instant;

/**
 * A distributed unique ID generator based on Twitter's Snowflake algorithm.
 *
 * <p>Structure (64 bits):
 * <pre>
 * 0 - 0000000000 0000000000 0000000000 0000000000 0 - 0000000000 - 000000000000
 * |   |←─────────── 41-bit timestamp ──────────→|  |← 10-bit →| |← 12-bit →|
 * |   |                                           | worker ID  |  sequence   |
 * unused                                        (milliseconds
 *                                               since epoch)
 * </pre>
 *
 * <p>Capable of generating ~409,600 IDs per second per worker. Generation is
 * thread-safe via method-level synchronization.
 *
 * <p>IDs can be decomposed via {@code parse(long)} for debugging and monitoring:
 * <pre>{@code
 * Snowflake sf = new Snowflake(1);
 * long id = sf.nextId();
 * Snowflake.IdInfo info = sf.parse(id);
 * info.timestamp();  // the Instant the ID was created
 * info.workerId();   // the worker that created it
 * info.sequence();   // the per-millisecond sequence number
 * }</pre>
 */
public final class Snowflake {

    /** Default epoch: 2020-01-01T00:00:00Z. */
    public static final long DEFAULT_EPOCH = 1577836800000L;

    private static final int WORKER_ID_BITS = 10;
    private static final int SEQUENCE_BITS = 12;

    private static final long MAX_WORKER_ID = (1L << WORKER_ID_BITS) - 1;   // 1023
    private static final long MAX_SEQUENCE = (1L << SEQUENCE_BITS) - 1;     // 4095

    private static final int TIMESTAMP_SHIFT = WORKER_ID_BITS + SEQUENCE_BITS;
    private static final int WORKER_ID_SHIFT = SEQUENCE_BITS;

    private final long epoch;
    private final long workerId;

    private long lastTimestamp = -1L;
    private long sequence = 0L;

    /**
     * Decomposed components of a snowflake ID.
     *
     * @param timestamp the instant the ID was generated
     * @param workerId  the worker that generated the ID
     * @param sequence  the per-millisecond sequence number
     */
    public record IdInfo(Instant timestamp, long workerId, long sequence) {}

    /**
     * Creates a Snowflake instance with the default epoch (2020-01-01T00:00:00Z).
     *
     * @param workerId worker ID, 0 to {@value #MAX_WORKER_ID}
     * @throws IllegalArgumentException if workerId is out of range
     */
    public Snowflake(long workerId) {
        this(workerId, DEFAULT_EPOCH);
    }

    /**
     * Creates a Snowflake instance with a custom epoch.
     *
     * @param workerId worker ID, 0 to {@value #MAX_WORKER_ID}
     * @param epoch    custom epoch in milliseconds since Unix epoch
     * @throws IllegalArgumentException if workerId is out of range or epoch is in the future
     */
    public Snowflake(long workerId, long epoch) {
        if (workerId < 0 || workerId > MAX_WORKER_ID) {
            throw new IllegalArgumentException(
                    "workerId must be in [0, " + MAX_WORKER_ID + "], got: " + workerId);
        }
        if (epoch > System.currentTimeMillis()) {
            throw new IllegalArgumentException("epoch must not be in the future: " + epoch);
        }
        this.workerId = workerId;
        this.epoch = epoch;
    }

    // ==================== Generation ====================

    /**
     * Generates the next unique ID.
     *
     * <p>If the system clock moves backwards (e.g. NTP adjustment), the generator
     * clamps to the last observed timestamp to guarantee monotonic uniqueness.
     * Only a sustained clock rollback combined with maximum throughput would cause
     * blocking until the clock catches up.
     *
     * @return a 64-bit snowflake ID
     */
    public synchronized long nextId() {
        long timestamp = System.currentTimeMillis();

        if (timestamp < lastTimestamp) {
            timestamp = lastTimestamp;
        }

        if (timestamp == lastTimestamp) {
            sequence = (sequence + 1) & MAX_SEQUENCE;
            if (sequence == 0) {
                timestamp = waitNextMillis(lastTimestamp);
            }
        } else {
            sequence = 0L;
        }

        lastTimestamp = timestamp;
        return ((timestamp - epoch) << TIMESTAMP_SHIFT)
                | (workerId << WORKER_ID_SHIFT)
                | sequence;
    }

    /**
     * Generates the next unique ID as a decimal string.
     *
     * @return a string representation of the next snowflake ID
     */
    public String nextString() {
        return Long.toString(nextId());
    }

    // ==================== Parsing / decomposition ====================

    /**
     * Decomposes an ID generated by this instance into its components.
     *
     * @param id a snowflake ID previously returned by this instance
     * @return the decomposed components
     */
    public IdInfo parse(long id) {
        return parse(id, this.epoch);
    }

    /**
     * Decomposes a snowflake ID using the given epoch.
     *
     * @param id    a snowflake ID
     * @param epoch the epoch that was used when generating the ID
     * @return the decomposed components
     */
    public static IdInfo parse(long id, long epoch) {
        long timestampMs = (id >> TIMESTAMP_SHIFT) + epoch;
        long workerId = (id >> WORKER_ID_SHIFT) & MAX_WORKER_ID;
        long sequence = id & MAX_SEQUENCE;
        return new IdInfo(Instant.ofEpochMilli(timestampMs), workerId, sequence);
    }

    /**
     * Extracts the generation timestamp from a snowflake ID, assuming the default epoch.
     *
     * @param id a snowflake ID
     * @return the instant the ID was generated
     */
    public static Instant extractTimestamp(long id) {
        return extractTimestamp(id, DEFAULT_EPOCH);
    }

    /**
     * Extracts the generation timestamp from a snowflake ID.
     *
     * @param id    a snowflake ID
     * @param epoch the epoch that was used when generating the ID
     * @return the instant the ID was generated
     */
    public static Instant extractTimestamp(long id, long epoch) {
        return Instant.ofEpochMilli((id >> TIMESTAMP_SHIFT) + epoch);
    }

    /**
     * Extracts the worker ID from a snowflake ID.
     *
     * @param id a snowflake ID
     * @return the worker ID (0–1023)
     */
    public static long extractWorkerId(long id) {
        return (id >> WORKER_ID_SHIFT) & MAX_WORKER_ID;
    }

    /**
     * Extracts the per-millisecond sequence number from a snowflake ID.
     *
     * @param id a snowflake ID
     * @return the sequence number (0–4095)
     */
    public static long extractSequence(long id) {
        return id & MAX_SEQUENCE;
    }

    // ==================== Internal ====================

    private static long waitNextMillis(long lastTimestamp) {
        long timestamp;
        do {
            Thread.onSpinWait();
            timestamp = System.currentTimeMillis();
        } while (timestamp <= lastTimestamp);
        return timestamp;
    }

    @Override
    public String toString() {
        return "Snowflake{workerId=" + workerId + ", epoch=" + Instant.ofEpochMilli(epoch) + "}";
    }
}
